databaseChangeLog:
  - changeSet:
      id: create-job-application-table
      author: aydanrahimova
      changes:
        - createTable:
            tableName: job_application
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: status
                  type: VARCHAR
              - column:
                  name: application_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: resume_url
                  type: VARCHAR
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_job_application_user
                    references: users(id)
              - column:
                  name: job_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_job_application_job
                    references: users(id)


